name: Release package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Push Go Module Version
        run: |
          git fetch --tags
          echo "Publishing Go module version: $(git describe --tags)"
          go list -m github.com/Nixotica/GbxRemoteGo@$(git describe --tags)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}